// SPDX-License-Identifier: MIT
// Emit spec/Sinew/RigRest.lean: per device node 0..14, the rest-world rotation (M3)
// of the SOMA bone it drives and the bone's toward-child long axis (RCSF +Y), read
// from the committed soma_rig.h.  play_log swings the long axis to the calibrated
// direction and carries the rest frame; the toward-child axis is consistent on both
// sides, unlike the rig's local +X (mirrored), so neither side flips.
//
//   g++ -I.. gen_rigrest.cpp -o gen_rigrest && ./gen_rigrest > ../spec/Sinew/RigRest.lean
#include <cmath>
#include <cstdio>
#include <cstring>

#include "soma_rig.h"

struct Map {
	const char *reb, *soma, *child;
};
// device node order 0..14 → SOMA joint name (matches anny_demo's kMap), plus the
// child joint whose direction defines the bone's toward-child long axis (RCSF +Y).
static const Map kMap[] = {{"Hips", "Hips", "Spine1"},
                           {"LeftUpperLeg", "LeftLeg", "LeftShin"},
                           {"RightUpperLeg", "RightLeg", "RightShin"},
                           {"LeftLowerLeg", "LeftShin", "LeftFoot"},
                           {"RightLowerLeg", "RightShin", "RightFoot"},
                           {"LeftFoot", "LeftFoot", "LeftToeBase"},
                           {"RightFoot", "RightFoot", "RightToeBase"},
                           {"Chest", "Chest", "Neck1"},
                           {"Head", "Head", "HeadEnd"},
                           {"LeftUpperArm", "LeftArm", "LeftForeArm"},
                           {"RightUpperArm", "RightArm", "RightForeArm"},
                           {"LeftLowerArm", "LeftForeArm", "LeftHand"},
                           {"RightLowerArm", "RightForeArm", "RightHand"},
                           {"LeftHand", "LeftHand", "LeftHandMiddle1"},
                           {"RightHand", "RightHand", "RightHandMiddle1"}};

static int jointByName(const char *n) {
	for (int j = 0; j < SOMA_J; j++) {
		if (strcmp(soma_jointNames[j], n) == 0) {
			return j;
		}
	}
	return -1;
}

int main() {
	printf("-- SPDX-License-Identifier: MIT\n");
	printf("-- Generated by viz_native/gen_rigrest.cpp from soma_rig.h: the rest-world\n");
	printf("-- rotation (M3) of the SOMA bone each device node 0..14 drives.  Local +X is\n");
	printf("-- the bone's long axis; world is +X left, +Y up, +Z forward.\n");
	printf("import Sinew.Math\n\nnamespace Sinew.RigRest\nopen Sinew.Math\n\n");
	printf("/-- Rest-world rotation of the SOMA bone driven by device node i (0..14). -/\n");
	printf("def restWorld : Array M3 := #[\n");
	for (int i = 0; i < 15; i++) {
		int j = jointByName(kMap[i].soma);
		const float *m = &soma_restWorld[j * 16];
		printf("  -- %2d %s (%s)\n", i, kMap[i].reb, kMap[i].soma);
		printf("  ⟨⟨%.9f, %.9f, %.9f⟩, ⟨%.9f, %.9f, %.9f⟩, ⟨%.9f, %.9f, %.9f⟩⟩%s\n", m[0], m[1],
		       m[2], m[4], m[5], m[6], m[8], m[9], m[10], i < 14 ? "," : "");
	}
	printf("]\n\n");
	printf("/-- Toward-child unit long axis (RCSF +Y) of each bone in world at rest. -/\n");
	printf("def restAxis : Array V3 := #[\n");
	for (int i = 0; i < 15; i++) {
		const float *pj = &soma_restWorld[jointByName(kMap[i].soma) * 16];
		const float *pc = &soma_restWorld[jointByName(kMap[i].child) * 16];
		float dx = pc[3] - pj[3], dy = pc[7] - pj[7], dz = pc[11] - pj[11];
		float n = std::sqrt(dx * dx + dy * dy + dz * dz);
		if (n < 1e-9f) {
			n = 1.0f;
		}
		printf("  ⟨%.9f, %.9f, %.9f⟩%s  -- %2d %s→%s\n", dx / n, dy / n, dz / n, i < 14 ? "," : "",
		       i, kMap[i].soma, kMap[i].child);
	}
	printf("]\n\n");

	// Rest offset from each node's parent tracked joint to it, expressed in the
	// parent's rest frame, so FK gives childPos = parentPos + Rparent·offset.
	static const int parent[15] = {255, 0, 0, 1, 2, 3, 4, 0, 7, 7, 7, 9, 10, 11, 12};
	printf("/-- Parent tracked node of each node 0..14 (15 = root). -/\n");
	printf("def parentNode : Array Nat := #[15, 0, 0, 1, 2, 3, 4, 0, 7, 7, 7, 9, 10, 11, 12]\n\n");
	printf("/-- Rest offset parent→joint in the parent's rest frame (FK lever arm). -/\n");
	printf("def restOffset : Array V3 := #[\n");
	for (int i = 0; i < 15; i++) {
		float lx = 0, ly = 0, lz = 0;
		if (parent[i] != 255) {
			const float *pn = &soma_restWorld[jointByName(kMap[i].soma) * 16];
			const float *pp = &soma_restWorld[jointByName(kMap[parent[i]].soma) * 16];
			float ox = pn[3] - pp[3], oy = pn[7] - pp[7], oz = pn[11] - pp[11];
			lx = pp[0] * ox + pp[4] * oy + pp[8] * oz;  // Rparentᵀ · offset_world
			ly = pp[1] * ox + pp[5] * oy + pp[9] * oz;
			lz = pp[2] * ox + pp[6] * oy + pp[10] * oz;
		}
		printf("  ⟨%.9f, %.9f, %.9f⟩%s  -- %2d %s\n", lx, ly, lz, i < 14 ? "," : "", i,
		       kMap[i].soma);
	}
	printf("]\n\nend Sinew.RigRest\n");
	return 0;
}
