// AUTO-GENERATED by bake/make_pheno.py — dims + byte offsets into soma_pheno.bin.
// Regenerate: pixi run -e export python bake/make_pheno.py
#pragma once

#define PH_P 13718
#define PH_V 18056
#define PH_J 78
#define PH_NB 624
#define PH_NVAR 26
#define PH_NFS 27420
#define PH_NNZ 33449
#define PH_BIN_BYTES 110202132

#define PH_OFF_template 0
#define PH_OFF_blend 164616
#define PH_OFF_mask 102885000
#define PH_OFF_F_src 102949896
#define PH_OFF_F_tet 103278936
#define PH_OFF_bary 103717656
#define PH_OFF_fids 104006552
#define PH_OFF_BW 104078776
#define PH_OFF_BSh 104083768
#define PH_OFF_SW 104300440
#define PH_OFF_par 109933912
#define PH_OFF_rbf_crow 109934224
#define PH_OFF_rbf_col 109934540
#define PH_OFF_rbf_val 110068336
